#!/usr/bin/env bash
# The visitor IP and HTTP status code from the Apache log file

# Making sure log file exist

LOG_FILE="apache-access.log"

if [[ ! -f $LOG_FILE ]]; then
    echo "Log file not found: $LOG_FILE"
    exit 1
fi

# Use awk to extract the IP and HTTP status code
awk '{print $1, $9}' "$LOG_FILE"
