#!/usr/bin/env bash
# We rae including the elif feature
i=1
while [ $i -le 10 ]
do
	if [ $i = 1 -le 4]
	then
		echo "bad luck"
	elif [ $i = 5 -le 7 ]
	then
		echo "good luck"
	fi
	else
		echo "Best School"
	fi
	((i++))
done 
