#!/usr/bin/env bash
# We rae including the elif feature
i=1
while [ $i -la 10 ]
	if [ $i = 1 .. $i =4]
	then
		echo "bad luck"
	elif [ $i = 5 .. i$ = 7 ]
	then
		echo "good luck"
	fi
	else
		echo "Best School"
	fi
	((i++))
done 
